Fix #6, add more features
Wenkrangha/BoatFly pull request #7
Opened 2024-03-23 12:44 UTC by Lumine1909

Bug fix:
https://github.com/Wenkrangha/BoatFly/issues/6

New features:
1. Tab complete support
2. Get flight boat directly by command

some implementation changes...

2024-03-23 14:49 UTC, Wenkrangha requested changes
我觉得部分地方需要修改

2024-03-23 14:49 UTC, Wenkrangha commented on src/main/java/com/wenkrang/boatfly/command/bf.java
关于获取飞船的命令是没必要的，在创造下，右键配方书可以直接获取飞船

2024-03-23 14:49 UTC, Wenkrangha commented on src/main/java/com/wenkrang/boatfly/event/GUI/KickEntity.java
> +        if (event.getView().getTitle().equalsIgnoreCase("飞船控制面包")/* isn't it "版"?*/) {
本来就是面包()

2024-03-23 14:49 UTC, Wenkrangha commented on src/main/java/com/wenkrang/boatfly/event/GUI/KickEntity.java
> +                        if (event.getWhoClicked().getVehicle().getPassengers().get(1) instanceof Player) {
很好的修复

2024-03-23 14:49 UTC, Wenkrangha commented on src/main/resources/plugin.yml
> +    default: op
实际上可以去掉

2024-03-23 14:56 UTC, Wenkrangha commented
你的更改我会考虑的

2024-03-23 15:06 UTC, Wenkrangha commented on src/main/java/com/wenkrang/boatfly/event/GUI/KickEntity.java
> +                            ((Player) event.getWhoClicked().getVehicle().getPassengers().get(0)).closeInventory();
有监听器监听了

2024-03-23 15:08 UTC, Wenkrangha commented
感谢你的提交，代码已采用，你的名字已加入贡献者列表

2024-03-23 15:08 UTC, closed without merging

2024-03-24 16:28 UTC, Lumine1909 commented on src/main/java/com/wenkrang/boatfly/command/bf.java
Should we add more info to the recipe book? I don't know that feature before you mentioned :(

2024-03-24 16:28 UTC, Lumine1909 commented on src/main/java/com/wenkrang/boatfly/event/GUI/KickEntity.java
> +        if (event.getView().getTitle().equalsIgnoreCase("飞船控制面包")/* isn't it "版"?*/) {
()

2024-03-24 16:31 UTC, Lumine1909 commented on src/main/java/com/wenkrang/boatfly/event/GUI/KickEntity.java
> +                            ((Player) event.getWhoClicked().getVehicle().getPassengers().get(0)).closeInventory();
I try it on paper-1.20.2-318, but the listener seems not work correctly.

After I click this button,
![image](https://github.com/Wenkrangha/BoatFly/assets/133463833/b7df5621-f24f-4fff-9774-b453b8a74869)


The panel still exist
![image](https://github.com/Wenkrangha/BoatFly/assets/133463833/9001c39f-dfd4-471f-b62b-98ea715300a9)

2024-03-24 16:37 UTC, Lumine1909 commented on src/main/java/com/wenkrang/boatfly/event/GUI/KickEntity.java
> +                            ((Player) event.getWhoClicked().getVehicle().getPassengers().get(0)).closeInventory();
![image](https://github.com/Wenkrangha/BoatFly/assets/133463833/54c4c51e-d5cb-4366-925f-43cbfbde1989)

com.wenkrang.boatfly.event.VehicleExit.java

Listener DO NOT close player's inventory when player exit the vehicle (the exit caused by kick from the panel).

2024-03-24 17:46 UTC, Lumine1909 commented on src/main/java/com/wenkrang/boatfly/event/GUI/KickEntity.java
> +                            ((Player) event.getWhoClicked().getVehicle().getPassengers().get(0)).closeInventory();
In addition, #6 may caused by this bug, when player kick itself and click the panel without ride on boat.